// ==UserScript==
// @name         Showdown Translation
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  test script
// @author       ceca3
// @match        http://china.psim.us/*
// @match        http://47.94.147.145.psim.us/*
// @grant        none
// @require      https://code.jQuery.com/jquery-2.1.4.min.js
// @run-at       document-end
// ==/UserScript==
var translations={
    "[Gen 7] Random Battle":"[第七世代] 随机对战",
    "Add game":"新对战",
    "Format:":"分级",
    "Team:":"队伍",
    "Battle!":"战斗！",
    "Find a random opponent":"寻找一位随机对手",
    "Teambuilder":"队伍编辑器",
    "Ladder":"排行榜",
    "Watch a battle":"观看对战",
    "Find a user":"查找用户",
    "Choice Scarf":"专爱围巾",
    "Did you have a good day?":"你今天过的还好吗?",
    "Lucario":"路卡利欧",
    "Lucarionite":"M路卡利欧石",
    "Adaptability":"适应力",
    "[Gen 7] OU battle started between":"[第七世代] OU比赛开始：",
    "and":" 和",
    "used":" 使用了",
    "The opposing":"对手的",
    "restored a little HP using its Leftovers!":"通过剩饭恢复了一点HP！",
    "forfeited":"认输了",
    "fainted!":"倒下了！",
    "Random team":"随机队伍",
    "Abilities":"特性",
    "Hidden Ability":"隐藏特性",
    "Will be":"Mega进化之后，特性将会变为",
    "after Mega Evolving.":"。",
    "Nickname":"昵称",
    "Item":"道具",
    "Ability":"特性",
    "Level":"等级",
    "Gender":"性别",
    "Happiness":"亲密度",
    "Shiny":"闪光",
    "Level:":"等级:",
    "Gender:":"性别:",
    "Happiness:":"亲密度:",
    "Shiny:":"闪光:",
    "Moves":"技能",
    "Copy":"复制",
    "Import/Export":"导入/导出",
    "Move":"移动",
    "Delete":"删除",
    "Team":" 队伍",
    "Validate":"确认是否合法",
    "Add Pokémon":"添加宝可梦",
    "New Team":"新的队伍",
    "Male":"雄性",
    "Female":"磁性",
    "Random":"随机",
    "Format List":" 分级列表",
    "List":" 列表",
    "Edit":"编辑",
    "Save":"保存",
    "Switch":"交换",
    "It's super effective!":"这非常有效！",
    "It's not very effective...":"这不是很有效...",
    "lost":"失去了 ",
    "of its health!":" 的生命值!",
    ", come back!":"，回来吧！",
    "(exists)":"(存在)",
    "Go!":"去吧！",
    "withdrew":"收回了",
    "sent out":"放出了",
    //Abilities Translation
    
    "Stench":"恶臭",
    "Drizzle":"降雨",
    "Speed Boost":"加速",
    "Battle Armor":"战斗盔甲",
    "Sturdy":"结实",
    "Damp":"湿气",
    "Limber":"柔软",
    "Sand Veil":"沙隐",
    "Static":"静电",
    "Volt Absorb":"蓄电",
    "Water Absorb":"储水",
    "Oblivious":"迟钝",
    "Cloud Nine":"无关天气",
    "Compound Eyes":"复眼",
    "Insomnia":"不眠",
    "Color Change":"变色",
    "Immunity":"免疫",
    "Flash Fire":"引火",
    "Shield Dust":"鳞粉",
    "Own Tempo":"我行我素",
    "Suction Cups":"吸盘",
    "Intimidate":"威吓",
    "Shadow Tag":"踩影",
    "Rough Skin":"粗糙皮肤",
    "Wonder Guard":"神奇守护",
    "Levitate":"飘浮",
    "Effect Spore":"孢子",
    "Synchronize":"同步",
    "Clear Body":"恒净之躯",
    "Natural Cure":"自然回复",
    "Lightning Rod":"避雷针",
    "Serene Grace":"天恩",
    "Swift Swim":"悠游自如",
    "Chlorophyll":"叶绿素",
    "Illuminate":"发光",
    "Trace":"复制",
    "Huge Power":"大力士",
    "Poison Point":"毒刺",
    "Inner Focus":"精神力",
    "Magma Armor":"熔岩铠甲",
    "Water Veil":"水幕",
    "Magnet Pull":"磁力",
    "Soundproof":"隔音",
    "Rain Dish":"雨盘",
    "Sand Stream":"扬沙",
    "Pressure":"压迫感",
    "Thick Fat":"厚脂肪",
    "Early Bird":"早起",
    "Flame Body":"火焰之躯",
    "Run Away":"逃跑",
    "Keen Eye":"锐利目光",
    "Hyper Cutter":"怪力钳",
    "Pickup":"捡拾",
    "Truant":"懒惰",
    "Hustle":"活力",
    "Cute Charm":"迷人之躯",
    "Plus":"正电",
    "Minus":"负电",
    "Forecast":"阴晴不定",
    "Sticky Hold":"黏着",
    "Shed Skin":"蜕皮",
    "Guts":"毅力",
    "Marvel Scale":"神奇鳞片",
    "Liquid Ooze":"污泥浆",
    "Overgrow":"茂盛",
    "Blaze":"猛火",
    "Torrent":"激流",
    "Swarm":"虫之预感",
    "Rock Head":"坚硬脑袋",
    "Drought":"日照",
    "Arena Trap":"沙穴",
    "Vital Spirit":"干劲",
    "White Smoke":"白色烟雾",
    "Pure Power":"瑜珈之力",
    "Shell Armor":"硬壳盔甲",
    "Air Lock":"气闸",
    "Tangled Feet":"蹒跚",
    "Motor Drive":"电气引擎",
    "Rivalry":"斗争心",
    "Steadfast":"不屈之心",
    "Snow Cloak":"雪隐",
    "Gluttony":"贪吃鬼",
    "Anger Point":"愤怒穴位",
    "Unburden":"轻装",
    "Heatproof":"耐热",
    "Simple":"单纯",
    "Dry Skin":"干燥皮肤",
    "Download":"下载",
    "Iron Fist":"铁拳",
    "Poison Heal":"毒疗",
    "Adaptability":"适应力",
    "Skill Link":"连续攻击",
    "Hydration":"湿润之躯",
    "Solar Power":"太阳之力",
    "Quick Feet":"飞毛腿",
    "Normalize":"一般皮肤",
    "Sniper":"狙击手",
    "Magic Guard":"魔法防守",
    "No Guard":"无防守",
    "Stall":"慢出",
    "Technician":"技术高手",
    "Leaf Guard":"叶子防守",
    "Klutz":"笨拙",
    "Mold Breaker":"破格",
    "Super Luck":"超幸运",
    "Aftermath":"引爆",
    "Anticipation":"危险预知",
    "Forewarn":"预知梦",
    "Unaware":"纯朴",
    "Tinted Lens":"有色眼镜",
    "Filter":"过滤",
    "Slow Start":"慢启动",
    "Scrappy":"胆量",
    "Storm Drain":"引水",
    "Ice Body":"冰冻之躯",
    "Solid Rock":"坚硬岩石",
    "Snow Warning":"降雪",
    "Honey Gather":"集蜜",
    "Frisk":"察觉",
    "Reckless":"舍身",
    "Multitype":"多属性",
    "Flower Gift":"花之礼",
    "Bad Dreams":"梦魇",
    "Pickpocket":"顺手牵羊",
    "Sheer Force":"强行",
    "Contrary":"唱反调",
    "Unnerve":"紧张感",
    "Defiant":"不服输",
    "Defeatist":"软弱",
    "Cursed Body":"诅咒之躯",
    "Healer":"治愈之心",
    "Friend Guard":"友情防守",
    "Weak Armor":"碎裂铠甲",
    "Heavy Metal":"重金属",
    "Light Metal":"轻金属",
    "Multiscale":"多重鳞片",
    "Toxic Boost":"中毒激升",
    "Flare Boost":"受热激升",
    "Harvest":"收获",
    "Telepathy":"心灵感应",
    "Moody":"心情不定",
    "Overcoat":"防尘",
    "Poison Touch":"毒手",
    "Regenerator":"再生力",
    "Big Pecks":"健壮胸肌",
    "Sand Rush":"泼沙",
    "Wonder Skin":"奇迹皮肤",
    "Analytic":"分析",
    "Illusion":"幻觉",
    "Imposter":"变身者",
    "Infiltrator":"穿透",
    "Mummy":"木乃伊",
    "Moxie":"自信过度",
    "Justified":"正义之心",
    "Rattled":"胆怯",
    "Magic Bounce":"魔法镜",
    "Sap Sipper":"食草",
    "Prankster":"恶作剧之心",
    "Sand Force":"沙之力",
    "Iron Barbs":"铁刺",
    "Zen Mode":"达摩模式",
    "Victory Star":"胜利之星",
    "Turboblaze":"涡轮火焰",
    "Teravolt":"兆级电压",
    "Aerilate":"飞行皮肤",
    "Aura Break":"气场破坏",
    "Cheek Pouch":"颊囊",
    "Dark Aura":"暗黑气场",
    "Fairy Aura":"妖精气场",
    "Flower Veil":"花幕",
    "Fur Coat":"毛皮大衣",
    "Mega Launcher":"超级发射器",
    "Parental Bond":"亲子爱",
    "Pixilate":"妖精皮肤",
    "Protean":"变幻自如",
    "Refrigerate":"冰冻皮肤",
    "Stance Change":"战斗切换",
    "Strong Jaw":"强壮之颚",
    "Sweet Veil":"甜幕",
    "Tough Claws":"硬爪",
    "Competitive":"好胜",
    "Gale Wings":"疾风之翼",
    "Gooey":"黏滑",
    "Aroma Veil":"芳香幕",
    "Bulletproof":"防弹",
    "Grass Pelt":"草之毛皮",
    "Magician":"魔术师",
    "Symbiosis":"共生",
    "Desolate Land":"终结之地",
    "Primordial Sea":"始源之海",
    "Delta Stream":"德尔塔气流",
    "Full Metal Body":"金属防护",
    "Shadow Shield":"幻影防守",
    "Comatose":"绝对睡眠",
    "Power Construct":"群聚变形",
    "Soul-Heart":"魂心",
    "Stakeout":"监视",
    "Electric Surge":"电气制造者",
    "Dazzling":"鲜艳之躯",
    "Berserk":"怒火冲天",
    "Battery":"蓄电池",
    "Corrosion":"腐蚀",
    "Disguise":"画皮",
    "Fluffy":"毛茸茸",
    "Stamina":"持久力",
    "Triage":"先行治疗",
    "Wimp Out":"跃跃欲逃",
    "Dancer":"舞者",
    "Shields Down":"界限盾壳",
    "Innards Out":"飞出的内在物",
    "Schooling":"鱼群",
    "Surge Surfer":"冲浪之尾",
    "Water Compaction":"遇水凝固",
    "Queenly Majesty":"女王的威严",
    "Battle Bond":"牵绊变身",
    "Receiver":"接球手",
    "RKS System":"ＡＲ系统",
    "Psychic Surge":"精神制造者",
    "Grassy Surge":"青草制造者",
    "Misty Surge":"薄雾制造者",
    "Slush Rush":"拨雪",
    "Emergency Exit":"危险回避",
    "Merciless":"不仁不义",
    "Water Bubble":"水泡",
    "Steelworker":"钢能力者",
    "Long Reach":"远隔",
    "Liquid Voice":"湿润之声",
    "Galvanize":"电气皮肤",
    "Tangling Hair":"卷发",
    "Power of Alchemy":"化学之力",
    "Beast Boost":"异兽提升",
    "Prism Armor":"棱镜装甲",
    
    // Moves Translation
    
    "Pound":"拍击",
    "Karate Chop":"空手劈",
    "Double Slap":"连环巴掌",
    "Comet Punch":"连续拳",
    "Mega Punch":"百万吨重拳",
    "Pay Day":"聚宝功",
    "Fire Punch":"火焰拳",
    "Ice Punch":"冷冻拳",
    "Thunder Punch":"雷电拳",
    "Scratch":"抓",
    "Vice Grip":"夹住",
    "Guillotine":"断头钳",
    "Razor Wind":"旋风刀",
    "Swords Dance":"剑舞",
    "Cut":"居合斩",
    "Gust":"起风",
    "Wing Attack":"翅膀攻击",
    "Whirlwind":"吹飞",
    "Fly":"飞翔",
    "Bind":"绑紧",
    "Slam":"摔打",
    "Vine Whip":"藤鞭",
    "Stomp":"踩踏",
    "Double Kick":"二连踢",
    "Mega Kick":"百万吨重踢",
    "Jump Kick":"飞踢",
    "Rolling Kick":"回旋踢",
    "Sand Attack":"泼沙",
    "Headbutt":"头锤",
    "Horn Attack":"角撞",
    "Fury Attack":"乱击",
    "Horn Drill":"角钻",
    "Tackle":"撞击",
    "Body Slam":"泰山压顶",
    "Wrap":"紧束",
    "Take Down":"猛撞",
    "Thrash":"大闹一番",
    "Double-Edge":"舍身冲撞",
    "Tail Whip":"摇尾巴",
    "Poison Sting":"毒针",
    "Twineedle":"双针",
    "Pin Missile":"导弹针",
    "Leer":"瞪眼",
    "Bite":"咬住",
    "Growl":"叫声",
    "Roar":"吼叫",
    "Sing":"唱歌",
    "Supersonic":"超音波",
    "Sonic Boom":"音爆",
    "Disable":"定身法",
    "Acid":"溶解液",
    "Ember":"火花",
    "Flamethrower":"喷射火焰",
    "Mist":"白雾",
    "Water Gun":"水枪",
    "Hydro Pump":"水炮",
    "Surf":"冲浪",
    "Ice Beam":"冰冻光束",
    "Blizzard":"暴风雪",
    "Psybeam":"精神光线",
    "Bubble Beam":"泡沫光线",
    "Aurora Beam":"极光束",
    "Hyper Beam":"破坏光线",
    "Peck":"啄",
    "Drill Peck":"啄钻",
    "Submission":"地狱翻滚",
    "Low Kick":"踢倒",
    "Counter":"双倍奉还",
    "Seismic Toss":"地球上投",
    "Strength":"怪力",
    "Absorb":"吸取",
    "Mega Drain":"超级吸取",
    "Leech Seed":"寄生种子",
    "Growth":"生长",
    "Razor Leaf":"飞叶快刀",
    "Solar Beam":"日光束",
    "Poison Powder":"毒粉",
    "Stun Spore":"麻痹粉",
    "Sleep Powder":"催眠粉",
    "Petal Dance":"花瓣舞",
    "String Shot":"吐丝",
    "Dragon Rage":"龙之怒",
    "Fire Spin":"火焰旋涡",
    "Thunder Shock":"电击",
    "Thunderbolt":"十万伏特",
    "Thunder Wave":"电磁波",
    "Thunder":"打雷",
    "Rock Throw":"落石",
    "Earthquake":"地震",
    "Fissure":"地裂",
    "Dig":"挖洞",
    "Toxic":"剧毒",
    "Confusion":"念力",
    "Psychic":"精神强念",
    "Hypnosis":"催眠术",
    "Meditate":"瑜珈姿势",
    "Agility":"高速移动",
    "Quick Attack":"电光一闪",
    "Rage":"愤怒",
    "Teleport":"瞬间移动",
    "Night Shade":"黑夜魔影",
    "Mimic":"模仿",
    "Screech":"刺耳声",
    "Double Team":"影子分身",
    "Recover":"自我再生",
    "Harden":"变硬",
    "Minimize":"变小",
    "Smokescreen":"烟幕",
    "Confuse Ray":"奇异之光",
    "Withdraw":"缩入壳中",
    "Defense Curl":"变圆",
    "Barrier":"屏障",
    "Light Screen":"光墙",
    "Haze":"黑雾",
    "Reflect":"反射壁",
    "Focus Energy":"聚气",
    "Bide":"忍耐",
    "Metronome":"挥指",
    "Mirror Move":"鹦鹉学舌",
    "Self-Destruct":"自爆",
    "Egg Bomb":"炸蛋",
    "Lick":"舌舔",
    "Smog":"浊雾",
    "Sludge":"污泥攻击",
    "Bone Club":"骨棒",
    "Fire Blast":"大字炎爆",
    "Waterfall":"攀瀑",
    "Clamp":"贝壳夹击",
    "Swift":"高速星星",
    "Skull Bash":"火箭头锤",
    "Spike Cannon":"尖刺加农炮",
    "Constrict":"缠绕",
    "Amnesia":"瞬间失忆",
    "Kinesis":"折弯汤匙",
    "Soft-Boiled":"生蛋",
    "High Jump Kick":"飞膝踢",
    "Glare":"大蛇瞪眼",
    "Dream Eater":"食梦",
    "Poison Gas":"毒瓦斯",
    "Barrage":"投球",
    "Leech Life":"吸血",
    "Lovely Kiss":"恶魔之吻",
    "Sky Attack":"神鸟猛击",
    "Transform":"变身",
    "Bubble":"泡沫",
    "Dizzy Punch":"迷昏拳",
    "Spore":"蘑菇孢子",
    "Flash":"闪光",
    "Psywave":"精神波",
    "Splash":"跃起",
    "Acid Armor":"溶化",
    "Crabhammer":"蟹钳锤",
    "Explosion":"大爆炸",
    "Fury Swipes":"乱抓",
    "Bonemerang":"骨头回力镖",
    "Rest":"睡觉",
    "Rock Slide":"岩崩",
    "Hyper Fang":"必杀门牙",
    "Sharpen":"棱角化",
    "Conversion":"纹理",
    "Tri Attack":"三冲攻击",
    "Super Fang":"愤怒门牙",
    "Slash":"劈开",
    "Substitute":"替身",
    "Struggle":"挣扎",
    "Sketch":"写生",
    "Triple Kick":"三连踢",
    "Thief":"小偷",
    "Spider Web":"蛛网",
    "Mind Reader":"心之眼",
    "Nightmare":"恶梦",
    "Flame Wheel":"火焰轮",
    "Snore":"鼾声",
    "Curse":"诅咒",
    "Flail":"抓狂",
    "Conversion 2":"纹理２",
    "Aeroblast":"气旋攻击",
    "Cotton Spore":"棉孢子",
    "Reversal":"起死回生",
    "Spite":"怨恨",
    "Powder Snow":"细雪",
    "Protect":"守住",
    "Mach Punch":"音速拳",
    "Scary Face":"鬼面",
    "Feint Attack":"出奇一击",
    "Sweet Kiss":"天使之吻",
    "Belly Drum":"腹鼓",
    "Sludge Bomb":"污泥炸弹",
    "Mud-Slap":"掷泥",
    "Octazooka":"章鱼桶炮",
    "Spikes":"撒菱",
    "Zap Cannon":"电磁炮",
    "Foresight":"识破",
    "Destiny Bond":"同命",
    "Perish Song":"灭亡之歌",
    "Icy Wind":"冰冻之风",
    "Detect":"看穿",
    "Bone Rush":"骨棒乱打",
    "Lock-On":"锁定",
    "Outrage":"逆鳞",
    "Sandstorm":"沙暴",
    "Giga Drain":"终极吸取",
    "Endure":"挺住",
    "Charm":"撒娇",
    "Rollout":"滚动",
    "False Swipe":"点到为止",
    "Swagger":"虚张声势",
    "Milk Drink":"喝牛奶",
    "Spark":"电光",
    "Fury Cutter":"连斩",
    "Steel Wing":"钢翼",
    "Mean Look":"黑色目光",
    "Attract":"迷人",
    "Sleep Talk":"梦话",
    "Heal Bell":"治愈铃声",
    "Return":"报恩",
    "Present":"礼物",
    "Frustration":"迁怒",
    "Safeguard":"神秘守护",
    "Pain Split":"分担痛楚",
    "Sacred Fire":"神圣之火",
    "Magnitude":"震级",
    "Dynamic Punch":"爆裂拳",
    "Megahorn":"超级角击",
    "Dragon Breath":"龙息",
    "Baton Pass":"接棒",
    "Encore":"再来一次",
    "Pursuit":"追打",
    "Rapid Spin":"高速旋转",
    "Sweet Scent":"甜甜香气",
    "Iron Tail":"铁尾",
    "Metal Claw":"金属爪",
    "Vital Throw":"借力摔",
    "Morning Sun":"晨光",
    "Synthesis":"光合作用",
    "Moonlight":"月光",
    "Hidden Power":"觉醒力量",
    "Hidden Power Bug":"觉醒力量-虫",
    "Hidden Power Dark":"觉醒力量-恶",
    "Hidden Power Dragon":"觉醒力量-龙",
    "Hidden Power Electric":"觉醒力量-电",
    "Hidden Power Fairy":"觉醒力量-妖精",
    "Hidden Power Fighting":"觉醒力量-格斗",
    "Hidden Power Fire":"觉醒力量-火",
    "Hidden Power Flying":"觉醒力量-飞行",
    "Hidden Power Ghost":"觉醒力量-幽灵",
    "Hidden Power Grass":"觉醒力量-草",
    "Hidden Power Ground":"觉醒力量-地面",
    "Hidden Power Ice":"觉醒力量-冰",
    "Hidden Power Poison":"觉醒力量-毒",
    "Hidden Power Psychic":"觉醒力量-超能",
    "Hidden Power Rock":"觉醒力量-岩石",
    "Hidden Power Steel":"觉醒力量-钢",
    "Hidden Power Water":"觉醒力量-水",
    "Cross Chop":"十字劈",
    "Twister":"龙卷风",
    "Rain Dance":"求雨",
    "Sunny Day":"大晴天",
    "Crunch":"咬碎",
    "Mirror Coat":"镜面反射",
    "Psych Up":"自我暗示",
    "Extreme Speed":"神速",
    "Ancient Power":"原始力量",
    "Shadow Ball":"暗影球",
    "Future Sight":"预知未来",
    "Rock Smash":"碎岩",
    "Whirlpool":"潮旋",
    "Beat Up":"围攻",
    "Fake Out":"击掌奇袭",
    "Uproar":"吵闹",
    "Stockpile":"蓄力",
    "Spit Up":"喷出",
    "Swallow":"吞下",
    "Heat Wave":"热风",
    "Hail":"冰雹",
    "Torment":"无理取闹",
    "Flatter":"吹捧",
    "Will-O-Wisp":"鬼火",
    "Memento":"临别礼物",
    "Facade":"硬撑",
    "Focus Punch":"真气拳",
    "Smelling Salts":"清醒",
    "Follow Me":"看我嘛",
    "Nature Power":"自然之力",
    "Charge":"充电",
    "Taunt":"挑衅",
    "Helping Hand":"帮助",
    "Trick":"戏法",
    "Role Play":"扮演",
    "Wish":"祈愿",
    "Assist":"借助",
    "Ingrain":"扎根",
    "Superpower":"蛮力",
    "Magic Coat":"魔法反射",
    "Recycle":"回收利用",
    "Revenge":"报复",
    "Brick Break":"劈瓦",
    "Yawn":"哈欠",
    "Knock Off":"拍落",
    "Endeavor":"蛮干",
    "Eruption":"喷火",
    "Skill Swap":"特性互换",
    "Imprison":"封印",
    "Refresh":"焕然一新",
    "Grudge":"怨念",
    "Snatch":"抢夺",
    "Secret Power":"秘密之力",
    "Dive":"潜水",
    "Arm Thrust":"猛推",
    "Camouflage":"保护色",
    "Tail Glow":"萤火",
    "Luster Purge":"洁净光芒",
    "Mist Ball":"薄雾球",
    "Feather Dance":"羽毛舞",
    "Teeter Dance":"摇晃舞",
    "Blaze Kick":"火焰踢",
    "Mud Sport":"玩泥巴",
    "Ice Ball":"冰球",
    "Needle Arm":"尖刺臂",
    "Slack Off":"偷懒",
    "Hyper Voice":"巨声",
    "Poison Fang":"剧毒牙",
    "Crush Claw":"撕裂爪",
    "Blast Burn":"爆裂烈焰",
    "Hydro Cannon":"加农水炮",
    "Meteor Mash":"彗星拳",
    "Astonish":"惊吓",
    "Weather Ball":"气象球",
    "Aromatherapy":"芳香治疗",
    "Fake Tears":"假哭",
    "Air Cutter":"空气利刃",
    "Overheat":"过热",
    "Odor Sleuth":"气味侦测",
    "Rock Tomb":"岩石封锁",
    "Silver Wind":"银色旋风",
    "Metal Sound":"金属音",
    "Grass Whistle":"草笛",
    "Tickle":"挠痒",
    "Cosmic Power":"宇宙力量",
    "Water Spout":"喷水",
    "Signal Beam":"信号光束",
    "Shadow Punch":"暗影拳",
    "Extrasensory":"神通力",
    "Sky Uppercut":"冲天拳",
    "Sand Tomb":"流沙地狱",
    "Sheer Cold":"绝对零度",
    "Muddy Water":"浊流",
    "Bullet Seed":"种子机关枪",
    "Aerial Ace":"燕返",
    "Icicle Spear":"冰锥",
    "Iron Defense":"铁壁",
    "Block":"挡路",
    "Howl":"长嚎",
    "Dragon Claw":"龙爪",
    "Frenzy Plant":"疯狂植物",
    "Bulk Up":"健美",
    "Bounce":"弹跳",
    "Mud Shot":"泥巴射击",
    "Poison Tail":"毒尾",
    "Covet":"渴望",
    "Volt Tackle":"伏特攻击",
    "Magical Leaf":"魔法叶",
    "Water Sport":"玩水",
    "Calm Mind":"冥想",
    "Leaf Blade":"叶刃",
    "Dragon Dance":"龙之舞",
    "Rock Blast":"岩石爆击",
    "Shock Wave":"电击波",
    "Water Pulse":"水之波动",
    "Doom Desire":"破灭之愿",
    "Psycho Boost":"精神增压",
    "Roost":"羽栖",
    "Gravity":"重力",
    "Miracle Eye":"奇迹之眼",
    "Wake-Up Slap":"唤醒巴掌",
    "Hammer Arm":"臂锤",
    "Gyro Ball":"陀螺球",
    "Healing Wish":"治愈之愿",
    "Brine":"盐水",
    "Natural Gift":"自然之恩",
    "Feint":"佯攻",
    "Pluck":"啄食",
    "Tailwind":"顺风",
    "Acupressure":"点穴",
    "Metal Burst":"金属爆炸",
    "U-turn":"极速折返",
    "Close Combat":"近身战",
    "Payback":"以牙还牙",
    "Assurance":"恶意追击",
    "Embargo":"查封",
    "Fling":"投掷",
    "Psycho Shift":"精神转移",
    "Trump Card":"王牌",
    "Heal Block":"回复封锁",
    "Wring Out":"绞紧",
    "Power Trick":"力量戏法",
    "Gastro Acid":"胃液",
    "Lucky Chant":"幸运咒语",
    "Me First":"抢先一步",
    "Copycat":"仿效",
    "Power Swap":"力量互换",
    "Guard Swap":"防御互换",
    "Punishment":"惩罚",
    "Last Resort":"珍藏",
    "Worry Seed":"烦恼种子",
    "Sucker Punch":"突袭",
    "Toxic Spikes":"毒菱",
    "Heart Swap":"心灵交换",
    "Aqua Ring":"水流环",
    "Magnet Rise":"电磁漂浮",
    "Flare Blitz":"闪焰冲锋",
    "Force Palm":"发劲",
    "Aura Sphere":"波导弹",
    "Rock Polish":"岩石打磨",
    "Poison Jab":"毒击",
    "Dark Pulse":"恶之波动",
    "Night Slash":"暗袭要害",
    "Aqua Tail":"水流尾",
    "Seed Bomb":"种子炸弹",
    "Air Slash":"空气斩",
    "X-Scissor":"十字剪",
    "Bug Buzz":"虫鸣",
    "Dragon Pulse":"龙之波动",
    "Dragon Rush":"龙之俯冲",
    "Power Gem":"力量宝石",
    "Drain Punch":"吸取拳",
    "Vacuum Wave":"真空波",
    "Focus Blast":"真气弹",
    "Energy Ball":"能量球",
    "Brave Bird":"勇鸟猛攻",
    "Earth Power":"大地之力",
    "Switcheroo":"掉包",
    "Giga Impact":"终极冲击",
    "Nasty Plot":"诡计",
    "Bullet Punch":"子弹拳",
    "Avalanche":"雪崩",
    "Ice Shard":"冰砾",
    "Shadow Claw":"阴影爪",
    "Thunder Fang":"雷电牙",
    "Ice Fang":"冰冻牙",
    "Fire Fang":"火焰牙",
    "Shadow Sneak":"影子偷袭",
    "Mud Bomb":"泥巴炸弹",
    "Psycho Cut":"精神利刃",
    "Zen Headbutt":"意念头槌",
    "Mirror Shot":"镜光射击",
    "Flash Cannon":"加农光炮",
    "Rock Climb":"攀岩",
    "Defog":"清除浓雾",
    "Trick Room":"戏法空间",
    "Draco Meteor":"流星群",
    "Discharge":"放电",
    "Lava Plume":"喷烟",
    "Leaf Storm":"飞叶风暴",
    "Power Whip":"强力鞭打",
    "Rock Wrecker":"岩石炮",
    "Cross Poison":"十字毒刃",
    "Gunk Shot":"垃圾射击",
    "Iron Head":"铁头",
    "Magnet Bomb":"磁铁炸弹",
    "Stone Edge":"尖石攻击",
    "Captivate":"诱惑",
    "Stealth Rock":"隐形岩",
    "Grass Knot":"打草结",
    "Chatter":"喋喋不休",
    "Judgment":"制裁光砾",
    "Bug Bite":"虫咬",
    "Charge Beam":"充电光束",
    "Wood Hammer":"木槌",
    "Aqua Jet":"水流喷射",
    "Attack Order":"攻击指令",
    "Defend Order":"防御指令",
    "Heal Order":"回复指令",
    "Head Smash":"双刃头锤",
    "Double Hit":"二连击",
    "Roar of Time":"时光咆哮",
    "Spacial Rend":"亚空裂斩",
    "Lunar Dance":"新月舞",
    "Crush Grip":"捏碎",
    "Magma Storm":"熔岩风暴",
    "Dark Void":"暗黑洞",
    "Seed Flare":"种子闪光",
    "Ominous Wind":"奇异之风",
    "Shadow Force":"暗影潜袭",
    "Hone Claws":"磨爪",
    "Wide Guard":"广域防守",
    "Guard Split":"防御平分",
    "Power Split":"力量平分",
    "Wonder Room":"奇妙空间",
    "Psyshock":"精神冲击",
    "Venoshock":"毒液冲击",
    "Autotomize":"身体轻量化",
    "Rage Powder":"愤怒粉",
    "Telekinesis":"意念移物",
    "Magic Room":"魔法空间",
    "Smack Down":"击落",
    "Storm Throw":"山岚摔",
    "Flame Burst":"烈焰溅射",
    "Sludge Wave":"污泥波",
    "Quiver Dance":"蝶舞",
    "Heavy Slam":"重磅冲撞",
    "Synchronoise":"同步干扰",
    "Electro Ball":"电球",
    "Soak":"浸水",
    "Flame Charge":"蓄能焰袭",
    "Coil":"盘蜷",
    "Low Sweep":"下盘踢",
    "Acid Spray":"酸液炸弹",
    "Foul Play":"欺诈",
    "Simple Beam":"单纯光束",
    "Entrainment":"找伙伴",
    "After You":"您先请",
    "Round":"轮唱",
    "Echoed Voice":"回声",
    "Chip Away":"逐步击破",
    "Clear Smog":"清除之烟",
    "Stored Power":"辅助力量",
    "Quick Guard":"快速防守",
    "Ally Switch":"交换场地",
    "Scald":"热水",
    "Shell Smash":"破壳",
    "Heal Pulse":"治愈波动",
    "Hex":"祸不单行",
    "Sky Drop":"自由落体",
    "Shift Gear":"换挡",
    "Circle Throw":"巴投",
    "Incinerate":"烧尽",
    "Quash":"延后",
    "Acrobatics":"杂技",
    "Reflect Type":"镜面属性",
    "Retaliate":"报仇",
    "Final Gambit":"搏命",
    "Bestow":"传递礼物",
    "Inferno":"炼狱",
    "Water Pledge":"水之誓约",
    "Fire Pledge":"火之誓约",
    "Grass Pledge":"草之誓约",
    "Volt Switch":"伏特替换",
    "Struggle Bug":"虫之抵抗",
    "Bulldoze":"重踏",
    "Frost Breath":"冰息",
    "Dragon Tail":"龙尾",
    "Work Up":"自我激励",
    "Electroweb":"电网",
    "Wild Charge":"疯狂伏特",
    "Drill Run":"直冲钻",
    "Dual Chop":"二连劈",
    "Heart Stamp":"爱心印章",
    "Horn Leech":"木角",
    "Sacred Sword":"圣剑",
    "Razor Shell":"贝壳刃",
    "Heat Crash":"高温重压",
    "Leaf Tornado":"青草搅拌器",
    "Steamroller":"疯狂滚压",
    "Cotton Guard":"棉花防守",
    "Night Daze":"暗黑爆破",
    "Psystrike":"精神击破",
    "Tail Slap":"扫尾拍打",
    "Hurricane":"暴风",
    "Head Charge":"爆炸头撞击",
    "Gear Grind":"齿轮飞盘",
    "Searing Shot":"火焰弹",
    "Techno Blast":"高科技光炮",
    "Relic Song":"古老之歌",
    "Secret Sword":"神秘之剑",
    "Glaciate":"冰封世界",
    "Bolt Strike":"雷击",
    "Blue Flare":"青焰",
    "Fiery Dance":"火之舞",
    "Freeze Shock":"冰冻伏特",
    "Ice Burn":"极寒冷焰",
    "Snarl":"大声咆哮",
    "Icicle Crash":"冰柱坠击",
    "V-create":"V热焰",
    "Fusion Flare":"交错火焰",
    "Fusion Bolt":"交错闪电",
    "Baby-Doll Eyes":"圆瞳",
    "Boomburst":"爆音波",
    "Crafty Shield":"戏法防守",
    "Dazzling Gleam":"魔法闪耀",
    "Draining Kiss":"吸收之吻",
    "Fairy Wind":"妖精之风",
    "Flying Press":"飞身重压",
    "Forest's Curse":"森林诅咒",
    "Freeze-Dry":"冷冻干燥",
    "Geomancy":"大地掌控",
    "Petal Blizzard":"落英缤纷",
    "Infestation":"死缠烂打",
    "Moonblast":"月亮之力",
    "Mystical Fire":"魔法火焰",
    "Noble Roar":"战吼",
    "Nuzzle":"蹭蹭脸颊",
    "Oblivion Wing":"死亡之翼",
    "Parabolic Charge":"抛物面充电",
    "Phantom Force":"潜灵奇袭",
    "Play Rough":"嬉闹",
    "Play Nice":"和睦相处",
    "Trick-or-Treat":"万圣夜",
    "Water Shuriken":"飞水手里剑",
    "Aromatic Mist":"芳香薄雾",
    "Belch":"打嗝",
    "Confide":"密语",
    "Disarming Voice":"魅惑之声",
    "Eerie Impulse":"怪异电波",
    "Electric Terrain":"电气场地",
    "Electrify":"输电",
    "Fairy Lock":"妖精之锁",
    "Fell Stinger":"致命针刺",
    "Flower Shield":"鲜花防守",
    "Grassy Terrain":"青草场地",
    "Ion Deluge":"等离子浴",
    "King's Shield":"王者盾牌",
    "Land's Wrath":"大地神力",
    "Magnetic Flux":"磁场操控",
    "Mat Block":"掀榻榻米",
    "Misty Terrain":"薄雾场地",
    "Parting Shot":"抛下狠话",
    "Powder":"粉尘",
    "Power-Up Punch":"增强拳",
    "Rototiller":"耕地",
    "Spiky Shield":"尖刺防守",
    "Sticky Web":"黏黏网",
    "Topsy-Turvy":"颠倒",
    "Venom Drench":"毒液陷阱",
    "Happy Hour":"欢乐时光",
    "Celebrate":"庆祝",
    "Hold Back":"手下留情",
    "Diamond Storm":"钻石风暴 ",
    "Light of Ruin":"破灭之光",
    "Steam Eruption":"蒸汽爆炸",
    "Hyperspace Hole":"异次元洞",
    "Hold Hands":"牵手",
    "Thousand Arrows":"千箭齐发",
    "Thousand Waves":"千波激荡",
    "Origin Pulse":"根源波动",
    "Precipice Blades":"断崖之剑",
    "Dragon Ascent":"画龙点睛",
    "Hyperspace Fury":"异次元猛攻",
    "Core Enforcer":"核心惩罚者",
    "Fleur Cannon":"花朵加农炮",
    "High Horsepower":"十万马力",
    "Leafage":"树叶",
    "Moongeist Beam":"暗影之光",
    "Nature's Madness":"自然之怒",
    "Revelation Dance":"觉醒之舞",
    "Shell Trap":"陷阱甲壳",
    "Solar Blade":"日光刃",
    "Sunsteel Strike":"流星闪冲",
    "Accelerock":"冲岩",
    "Psychic Terrain":"精神场地",
    "Throat Chop":"地狱突刺",
    "Aurora Veil":"极光幕",
    "Laser Focus":"磨砺",
    "Clanging Scales":"鳞片噪音",
    "Multi-Attack":"多属性攻击",
    "Trop Kick":"热带踢",
    "Dragon Hammer":"龙锤",
    "Instruct":"号令",
    "Spirit Shackle":"缝影",
    "Darkest Lariat":"ＤＤ金勾臂",
    "Sparkling Aria":"泡影的咏叹",
    "Shore Up":"集沙",
    "First Impression":"迎头一击",
    "Baneful Bunker":"碉堡",
    "Ice Hammer":"冰锤",
    "Floral Healing":"花疗",
    "Strength Sap":"吸取力量",
    "Spotlight":"聚光灯",
    "Toxic Thread":"毒丝",
    "Gear Up":"辅助齿轮",
    "Pollen Puff":"花粉团",
    "Anchor Shot":"掷锚",
    "Lunge":"猛扑",
    "Fire Lash":"火焰鞭",
    "Power Trip":"嚣张",
    "Burn Up":"燃尽",
    "Speed Swap":"速度互换",
    "Smart Strike":"修长之角",
    "Purify":"净化",
    "Beak Blast":"鸟嘴加农炮",
    "Brutal Swing":"狂舞挥打",
    "Psychic Fangs":"精神之牙",
    "Stomping Tantrum":"跺脚",
    "Shadow Bone":"暗影之骨",
    "Liquidation":"水流裂破",
    "Prismatic Laser":"棱镜镭射",
    "Spectral Thief":"暗影偷盗",
    "Tearful Look":"泪眼汪汪",
    "Zing Zap":"麻麻刺刺",
    "Breakneck Blitz":"究极无敌大冲撞",
    "All-Out Pummeling":"全力无双激烈拳",
    "Supersonic Skystrike":"极速俯冲轰烈撞",
    "Acid Downpour":"强酸剧毒灭绝雨",
    "Tectonic Rage":"地隆啸天大终结",
    "Continental Crush":"毁天灭地巨岩坠",
    "Savage Spin-out":"绝对捕食回旋斩",
    "Never-Ending Nightmare":"无尽暗夜之诱惑",
    "Corkscrew Crash":"超绝螺旋连击",
    "Inferno Overdrive":"超强极限爆焰弹",
    "Hydro Vortex":"超级水流大漩涡",
    "Bloom Doom":"绚烂缤纷花怒放",
    "Gigavolt Havoc":"终极伏特狂雷闪",
    "Shattered Psyche":"至高精神破坏波",
    "Subzero Slammer":"激狂大地万里冰",
    "Devastating Drake":"究极巨龙震天地",
    "Black Hole Eclipse":"黑洞吞噬万物灭",
    "Twinkle Tackle":"可爱星星飞天撞",
    "Catastropika":"皮卡皮卡必杀击",
    "Stoked Sparksurfer":"驾雷驭电戏冲浪",
    "Extreme Evoboost":"九彩升华齐聚顶",
    "Pulverizing Pancake":"认真起来大爆击",
    "Genesis Supernova":"起源超新星大爆炸",
    "Guardian of Alola":"巨人卫士-阿罗拉",
    "Sinister Arrow Raid":"遮天蔽日暗影箭",
    "Malicious Moonsault":"极恶飞跃粉碎击",
    "Oceanic Operetta":"海神庄严交响乐",
    "Soul-Stealing 7-Star Strike":"七星夺魂腿",
    "10,000,Volt Thunderbolt":"千万伏特",
    
    // Items Translation
    
    "Big Root":"大根",
    "Blue Scarf":"蓝色丝巾",
    "Bright Powder":"光粉",
    "Choice Band":"专爱头巾",
    "Choice Scarf":"专爱围巾",
    "Choice Specs":"专爱眼镜",
    "Destiny Knot":"红色丝线",
    "Expert Belt":"达人腰带",
    "Focus Band":"气息头巾",
    "Focus Sash":"气息腰带",
    "Full Incense":"满腹香炉",
    "Green Scarf":"绿色丝巾",
    "Lagging Tail":"后攻尾",
    "Lax Incense":"无虑香炉",
    "Leftovers":"剩饭",
    "Luck Incense":"好运香炉",
    "Mental Herb":"精神药草",
    "Metal Powder":"金属粉末",
    "Muscle Band":"力量头巾",
    "Odd Incense":"怪异香炉",
    "Pink Scarf":"粉红丝巾",
    "Power Herb":"力量药草",
    "Pure Incense":"清静香炉",
    "Quick Powder":"速度粉末",
    "Reaper Cloth":"灵界幕布",
    "Red Scarf":"红色丝巾",
    "Rock Incense":"岩石香炉",
    "Rose Incense":"花朵香炉",
    "Sea Incense":"潮水香炉",
    "Shed Shell":"绚丽外壳",
    "Silk Scarf":"丝绸围巾",
    "Silver Powder":"银色粉末",
    "Smooth Rock":"光滑岩石",
    "Soft Sand":"软沙",
    "Soothe Bell":"安闲铃",
    "Wave Incense":"细波香炉",
    "White Herb":"白色药草",
    "Wide Lens":"广角镜",
    "Wise Glasses":"智慧眼镜",
    "Yellow Scarf":"黄色丝巾",
    "Zoom Lens":"瞄准镜",
    "Amulet Coin":"守护金币",
    "Antidote":"解毒药",
    "Awakening":"清醒药",
    "Berry Juice":"果汁",
    "Big Pearl":"大珍珠",
    "Big Mushroom":"大蘑菇",
    "Black Belt":"黑带",
    "Black Flute":"黑哨子",
    "Black Sludge":"黑色淤泥",
    "Black Glasses":"黑色眼镜",
    "Blue Flute":"蓝哨子",
    "Blue Shard":"蓝色碎片",
    "Burn Heal":"烧伤药",
    "Calcium":"特攻努力药",
    "Carbos":"速度努力药",
    "Charcoal":"木炭",
    "Cleanse Tag":"清静符",
    "Damp Mulch":"缓慢肥料",
    "Deep Sea Scale":"深海之鳞",
    "Dire Hit":"会心胶囊",
    "Dragon Scale":"龙鳞",
    "Elixir":"PP全回复",
    "Energy Root":"力量根",
    "Energy Powder":"力量粉末",
    "Escape Rope":"穿洞绳",
    "Ether":"PP回复",
    "Everstone":"不变石",
    "Exp. Share":"学习装置",
    "Fire Stone":"火石",
    "Flame Orb":"火焰珠",
    "Fluffy Tail":"小猫尾巴",
    "Fresh Water":"美味水",
    "Full Heal":"万能恢复",
    "Full Restore":"恢复药",
    "Gooey Mulch":"粘粘肥料",
    "Green Shard":"绿色碎片",
    "Growth Mulch":"生长肥料",
    "Guard Spec.":"守护胶囊",
    "Heal Powder":"万能粉末",
    "Heart Scale":"心之鳞片",
    "Honey":"蜂蜜",
    "HP Up":"HP努力药",
    "Hyper Potion":"高级伤药",
    "Ice Heal":"冰冻恢复",
    "Iron":"物防努力药",
    "King's Rock":"王者之证",
    "Lava Cookie":"飞音饼",
    "Leaf Stone":"叶石",
    "Lemonade":"柠檬汁",
    "Life Orb":"生命玉",
    "Light Ball":"电珠",
    "Light Clay":"光之黏土",
    "Lucky Egg":"幸运蛋",
    "Magnet":"磁石",
    "Max Elixir":"PP全最大",
    "Max Ether":"PP最大",
    "Max Potion":"最大伤药",
    "Max Repel":"金色喷雾器",
    "Max Revive":"元气药块",
    "Metal Coat":"金属外套",
    "Metronome":"节拍器",
    "Miracle Seed":"奇迹之种",
    "Moomoo Milk":"哞哞牛奶",
    "Moon Stone":"月石",
    "Mystic Water":"神秘水滴",
    "Never-Melt Ice":"不融冰",
    "Nugget":"金珠",
    "Old Gateau":"森林羊羹",
    "Paralyze Heal":"麻痹恢复",
    "Pearl":"珍珠",
    "Poké Doll":"精灵玩偶",
    "Potion":"伤药",
    "PP Max":"PP最大",
    "PP Up":"PP上升",
    "Protein":"攻击努力药",
    "Rare Candy":"神奇糖果",
    "Razor Fang":"尖锐之牙",
    "Red Flute":"红哨子",
    "Red Shard":"红色碎片",
    "Repel":"除虫喷雾器",
    "Revival Herb":"复活药草",
    "Revive":"元气药片",
    "Sacred Ash":"圣灰",
    "Scope Lens":"聚焦镜",
    "Shell Bell":"空贝铃",
    "Shoal Salt":"浅水盐",
    "Shoal Shell":"浅水贝壳",
    "Smoke Ball":"烟珠",
    "Soda Pop":"美味苏打",
    "Soul Dew":"心之水滴",
    "Spell Tag":"诅咒符",
    "Stable Mulch":"延时肥料",
    "Star Piece":"星之碎片",
    "Stardust":"星砂",
    "Sun Stone":"日石",
    "Super Potion":"好伤药",
    "Super Repel":"银色喷雾器",
    "Thunder Stone":"雷石",
    "Tiny Mushroom":"小蘑菇",
    "Toxic Orb":"剧毒珠",
    "Twisted Spoon":"弯勺子",
    "Up-Grade":"升级包",
    "Water Stone":"水石",
    "White Flute":"白哨子",
    "X Accuracy":"命中胶囊",
    "X Attack":"攻击胶囊",
    "X Defend":"防御胶囊",
    "X Special":"特攻胶囊",
    "X Sp. Def":"特防胶囊",
    "X Speed":"速度胶囊",
    "Yellow Flute":"黄哨子",
    "Yellow Shard":"黄色碎片",
    "Zinc":"特防努力药",
    "Icy Rock":"寒冰岩石",
    "Lucky Punch":"幸运拳套",
    "Dubious Disc":"怪异补丁",
    "Sharp Beak":"尖锐鸟嘴",
    "Adamant Orb":"金刚玉",
    "Damp Rock":"潮湿岩石",
    "Heat Rock":"炽热岩石",
    "Lustrous Orb":"白玉",
    "Macho Brace":"竞争背心",
    "Stick":"长葱",
    "Dragon Fang":"龙之牙",
    "Poison Barb":"毒针",
    "Power Anklet":"力量护踝",
    "Power Band":"力量束带",
    "Power Belt":"力量腰带",
    "Power Bracer":"力量护腕",
    "Power Lens":"力量眼镜",
    "Power Weight":"力量束腰",
    "Dawn Stone":"觉醒石",
    "Dusk Stone":"暗石",
    "Electirizer":"电力助推器",
    "Magmarizer":"熔岩助推器",
    "Odd Keystone":"要石",
    "Oval Stone":"真丸石",
    "Protector":"保护器",
    "Quick Claw":"先制之爪",
    "Razor Claw":"尖锐之爪",
    "Shiny Stone":"光石",
    "Sticky Barb":"附针",
    "Deep Sea Tooth":"深海之牙",
    "Draco Plate":"龙之石板",
    "Dread Plate":"恐怖石板",
    "Earth Plate":"大地石板",
    "Fist Plate":"拳击石板",
    "Flame Plate":"火球石板",
    "Grip Claw":"粘附钩爪",
    "Icicle Plate":"冰柱石板",
    "Insect Plate":"昆虫石板",
    "Iron Plate":"钢铁石板",
    "Meadow Plate":"绿色石板",
    "Mind Plate":"神秘石板",
    "Sky Plate":"青空石板",
    "Splash Plate":"水滴石板",
    "Spooky Plate":"幽灵石板",
    "Stone Plate":"岩石石板",
    "Thick Club":"粗骨棒",
    "Toxic Plate":"剧毒石板",
    "Zap Plate":"雷电石板",
    "Armor Fossil":"盾牌化石",
    "Claw Fossil":"尖爪化石",
    "Dome Fossil":"甲壳化石",
    "Hard Stone":"坚硬岩石",
    "Helix Fossil":"贝克化石",
    "Old Amber":"秘密琥珀",
    "Rare Bone":"贵重骨棒",
    "Root Fossil":"草根化石",
    "Skull Fossil":"头盖化石",
    "Iron Ball":"黑铁球",
    "Griseous Orb":"白金玉",
    "Air Mail":"天空邮件",
    "Bloom Mail":"鲜花邮件",
    "Brick Mail":"瓦片邮件",
    "Bubble Mail":"蓝色邮件",
    "Flame Mail":"火焰邮件",
    "Grass Mail":"绿草邮件",
    "Harbor Mail":"港湾邮件",
    "Heart Mail":"爱情邮件",
    "Mosaic Mail":"马赛克邮件",
    "Snow Mail":"暴雪邮件",
    "Space Mail":"太空邮件",
    "Steel Mail":"钢铁邮件",
    "Tunnel Mail":"隧道邮件",
    "Douse Drive":"海洋卡带",
    "Shock Drive":"雷电卡带",
    "Burn Drive":"火焰卡带",
    "Chill Drive":"冰冻卡带",
    "Sweet Heart":"甜心",
    "Prism Scale":"洁净鳞片",
    "Eviolite":"进化辉石",
    "Float Stone":"浮石",
    "Rocky Helmet":"坚硬头盔",
    "Air Balloon":"气球",
    "Red Card":"红牌",
    "Ring Target":"狙击标靶",
    "Binding Band":"束缚头巾",
    "Absorb Bulb":"灯泡",
    "Cell Battery":"充电电池",
    "Eject Button":"逃生按钮",
    "Fire Gem":"火焰珠宝",
    "Water Gem":"水之珠宝",
    "Electric Gem":"闪电珠宝",
    "Grass Gem":"草之珠宝",
    "Ice Gem":"寒冰珠宝",
    "Fighting Gem":"格斗珠宝",
    "Poison Gem":"剧毒珠宝",
    "Ground Gem":"大地珠宝",
    "Flying Gem":"飞行珠宝",
    "Psychic Gem":"超能珠宝",
    "Bug Gem":"虫之珠宝",
    "Rock Gem":"岩石珠宝",
    "Ghost Gem":"幽灵珠宝",
    "Dragon Gem":"飞龙珠宝",
    "Dark Gem":"暗黑珠宝",
    "Steel Gem":"钢铁珠宝",
    "Normal Gem":"普通珠宝",
    "Health Wing":"强壮之羽",
    "Muscle Wing":"力量之羽",
    "Resist Wing":"阻力之翼",
    "Genius Wing":"智慧之翼",
    "Clever Wing":"心灵之翼",
    "Swift Wing":"瞬时之翼",
    "Pretty Wing":"美丽之翼",
    "Dream Ball":"梦之珠",
    "Balm Mushroom":"芳香蘑菇",
    "Big Nugget":"巨大金珠",
    "Pearl String":"巨大珍珠",
    "Comet Shard":"彗星碎片",
    "Relic Copper":"古代铜币",
    "Relic Silver":"古代银币",
    "Relic Gold":"古代金币",
    "Relic Vase":"古代花瓶",
    "Relic Band":"古代头盔",
    "Relic Statue":"古代雕像",
    "Relic Crown":"古代皇冠",
    "Casteliacone":"冰激凌",
    "Dire Hit 2":"致命攻击2",
    "X Speed 2":"速度强化2",
    "X Special 2":"特殊提升2",
    "X Sp. Def 2":"特殊防御2",
    "X Defend 2":"防御强化2",
    "X Attack 2":"力量强化2",
    "X Accuracy 2":"命中强化2",
    "X Speed 3":"速度强化3",
    "X Special 3":"特殊提升3",
    "X Sp. Def 3":"特殊防御3",
    "X Defend 3":"防御强化3",
    "X Attack 3":"力量强化3",
    "X Accuracy 3":"命中强化3",
    "X Speed 6":"速度强化6",
    "X Special 6":"特殊提升6",
    "X Sp. Def 6":"特殊防御6",
    "X Defend 6":"防御强化6",
    "X Attack 6":"力量强化6",
    "X Accuracy 6":"命中强化6",
    "Ability Urge":"特性召唤",
    "Item Drop":"道具丢弃",
    "Item Urge":"道具召唤",
    "Reset Urge":"还原召唤",
    "Dire Hit 3":"致命攻击3",
    "Berserk Gene":"疯狂基因",
    "Poké Ball":"怪兽球",
    "Great Ball":"超级球",
    "Ultra Ball":"特级球",
    "Master Ball":"大师球",
    "Safari Ball":"狩猎球",
    "Level Ball":"等级球",
    "Lure Ball":"诱饵球",
    "Moon Ball":"月亮球",
    "Friend Ball":"友谊球",
    "Love Ball":"爱心球",
    "Heavy Ball":"重量球",
    "Fast Ball":"速度球",
    "Sport Ball":"运动球",
    "Premier Ball":"贵宾球",
    "Repeat Ball":"重复球",
    "Timer Ball":"时间球",
    "Nest Ball":"巢球",
    "Net Ball":"网球",
    "Dive Ball":"潜水球",
    "Luxury Ball":"豪华球",
    "Heal Ball":"治愈球",
    "Quick Ball":"快速球",
    "Dusk Ball":"黑暗球",
    "Cherish Ball":"珍贵球",
    "Park Ball":"公园球",
    "Pixie Plate":"仙灵石板",
    "Assault Vest":"突击背心",
    "Safety Goggles":"安全护镜",
    "Weakness Policy":"弱点政策",
    "Snowball":"雪球",
    "Luminous Moss":"发光苔藓",
    "Ability Capsule":"特性胶囊",
    "Jaw Fossil":"颚之化石",
    "Sail Fossil":"鳍之化石",
    "Lumiose Galette":"光华格雷饼",
    "Sachet":"香袋",
    "Whipped Dream":"搅好的奶油",
    "Red Orb":"红色宝珠",
    "Blue Orb":"蓝色宝珠",
    "Fighting Memory":"格斗存储碟",
    "Flying Memory":"飞行存储碟",
    "Poison Memory":"毒存储碟",
    "Ground Memory":"大地存储碟",
    "Rock Memory":"岩石存储碟",
    "Bug Memory":"虫存储碟",
    "Ghost Memory":"鬼存储碟",
    "Steel Memory":"钢存储碟",
    "Fire Memory":" 存储碟",
    "Water Memory":"水存储碟",
    "Grass Memory":"草存储碟",
    "Electric Memory":"电存储碟",
    "Psychic Memory":"超能存储碟",
    "Ice Memory":"冰存储碟",
    "Dragon Memory":"龙存储碟",
    "Dark Memory":"黑暗存储碟",
    "Fairy Memory":"妖精存储碟",
    "Adrenaline Orb":"胆怯球",
    "Terrain Extender":"大地膜",
    "Protective Pads":"部位护具",
    "Electric Seed":"电气种子",
    "Psychic Seed":"精神种子",
    "Misty Seed":"薄雾种子",
    "Grassy Seed":"青草种子",
    "Beast Ball":"究极球",
    "Big Malasada":"大马拉萨达",
    "Common Stone":"常见石",
    "Bottle Cap":"银色王冠",
    "Gold Bottle Cap":"金色王冠",
    "Ice Stone":"冰之石",
    "Shalour Sable":"娑罗沙布蕾",
    "Pink Nectar":"桃粉色花蜜",
    "Yellow Nectar":"金黄色花蜜",
    "Red Nectar":"朱红色花蜜",
    "Purple Nectar":"兰紫色花蜜",
    "Pink Bow":"粉红缎带",
    "Polkadot Bow":"圆点缎带",
    "Venusaurite":"M妙蛙花石",
    "Charizardite X":"M喷火龙石X",
    "Charizardite Y":"M喷火龙石Y",
    "Blastoisinite":"M水箭龟石",
    "Alakazite":"M胡帝石",
    "Gengarite":"M耿鬼石",
    "Kangaskhanite":"M袋龙石",
    "Pinsirite":"M大甲石",
    "Gyaradosite":"M暴鲤龙石",
    "Aerodactylite":"M化石翼龙石",
    "Mewtwonite X":"M超梦石X",
    "Mewtwonite Y":"M超梦石Y",
    "Ampharosite":"M电龙石",
    "Scizorite":"M巨钳螳螂石",
    "Heracronite":"M甲虫兽石",
    "Houndoominite":"M地狱犬石",
    "Tyranitarite":"M班吉拉石",
    "Blazikenite":"M火焰鸡石",
    "Gardevoirite ":"M沙奈朵石",
    "Mawilite":"M大嘴娃石",
    "Aggronite":"M狂暴龙石",
    "Medichamite":"M瑜伽王石",
    "Manectite":"M雷电兽石",
    "Banettite":"M诅咒娃娃石",
    "Absolite":"M灾兽石",
    "Garchompite":"M地龙石",
    "Lucarionite":"M路卡利欧石",
    "Abomasite":"M暴雪王石",
    "Sceptilite":"M蜥蜴王石",
    "Swampertite":"M巨沼怪石",
    "Beedrillite":"M大针蜂石",
    "Pidgeotite":"M比雕石",
    "Slowbronite":"M呆河马石",
    "Steelixite":"M大钢蛇石",
    "Sablenite":"M勾魂眼石",
    "Sharpedonite":"M巨牙鲨石",
    "Cameruptite":"M喷火驼石",
    "Altarianite":"M七夕青鸟石",
    "Glalitite":"M冰鬼护石",
    "Salamencite":"M暴蝾螈石",
    "Metagrossite":"M巨金怪石",
    "Lopunnite":"M长耳兔石",
    "Galladite":"M超能斗士石",
    "Audinite":"M差不多娃娃石",
    "Diancite":"M蒂安希石",
    "Latiasite":"M拉提亚斯石",
    "Latiosite":"M拉提欧斯石",
    "Normalium Z":"一般Z纯晶",
    "Fightinium Z":"格斗Z纯晶",
    "Flyinium Z":"飞行 Z纯晶",
    "Poisonium Z":"毒Z纯晶",
    "Groundium Z":"地面 Z纯晶",
    "Rockium Z":"岩石Z纯晶",
    "Buginium Z":"虫Z纯晶",
    "Ghostium Z":"鬼Z纯晶",
    "Steelium Z":"钢Z纯晶",
    "Firium Z":"火Z纯晶",
    "Waterium Z":"水Z纯晶",
    "Grassium Z":"草Z纯晶",
    "Electrium Z":"电Z纯晶",
    "Psychium Z":"超能Z纯晶",
    "Icium Z":"冰Z纯晶",
    "Dragonium Z":"龙Z纯晶",
    "Darkinium Z":"恶Z纯晶",
    "Fairium Z":"仙Z纯晶",
    "Pikanium Z":"皮卡丘Z纯晶",
    "Aloraichium Z":"阿罗雷Z纯晶",
    "Eevium Z":"伊布Z纯晶",
    "Snorlium Z":"卡比兽Z纯晶",
    "Mewnium Z":"梦幻Z纯晶",
    "Tapunium Z":"卡璞Z纯晶",
    "Decidium Z":"狙射树枭Z纯晶",
    "Incinium Z":"炽焰咆哮虎Z纯晶",
    "Primarium Z":"西狮海壬Z纯晶",
    "Marshadium Z":"玛夏多Z纯晶",
    "Pikashunium Z":"小智皮卡丘Z纯晶",
    "Cheri Berry":"解麻果",
    "Chesto Berry":"醒睡果",
    "Pecha Berry":"解毒果",
    "Rawst Berry":"烧伤果",
    "Aspear Berry":"解冻果",
    "Leppa Berry":"海棠果",
    "Oran Berry":"橙果",
    "Persim Berry":"混乱果",
    "Lum Berry":"奇迹果",
    "Sitrus Berry":"文旦果",
    "Figy Berry":"11号果实",
    "Wiki Berry":"12号果实",
    "Mago Berry":"13号果实",
    "Aguav Berry":"14号果实",
    "Iapapa Berry":"15号果实",
    "Razz Berry":"16号果实",
    "Bluk Berry":"17号果实",
    "Nanab Berry":"18号果实",
    "Wepear Berry":"19号果实",
    "Pinap Berry":"20号果实",
    "Pomeg Berry":"21号果实",
    "Kelpsy Berry":"22号果实",
    "Qualot Berry":"23号果实",
    "Hondew Berry":"24号果实",
    "Grepa Berry":"25号果实",
    "Tamato Berry":"26号果实",
    "Cornn Berry":"27号果实",
    "Magost Berry":"28号果实",
    "Rabuta Berry":"29号果实",
    "Nomel Berry":"30号果实",
    "Spelon Berry":"31号果实",
    "Pamtre Berry":"32号果实",
    "Watmel Berry":"33号果实",
    "Durin Berry":"34号果实",
    "Belue Berry":"35号果实",
    "Occa Berry":"抗火果",
    "Passho Berry":"抗水果",
    "Wacan Berry":"抗电果",
    "Rindo Berry":"抗草果",
    "Yache Berry":"抗冰果",
    "Chople Berry":"抗格果",
    "Kebia Berry":"抗毒果",
    "Shuca Berry":"抗地果",
    "Coba Berry":"抗飞果",
    "Payapa Berry":"抗超果",
    "Tanga Berry":"抗虫果",
    "Charti Berry":"抗岩果",
    "Kasib Berry":"抗鬼果",
    "Haban Berry":"抗龙果",
    "Colbur Berry":"抗恶果",
    "Babiri Berry":"抗钢果",
    "Chilan Berry":"抗普果",
    "Liechi Berry":"物攻果",
    "Ganlon Berry":"物防果",
    "Salac Berry":"速度果",
    "Petaya Berry":"特攻果",
    "Apicot Berry":"特防果",
    "Lansat Berry":"会心果",
    "Starf Berry":"随机果",
    "Enigma Berry":"谜之果",
    "Micle Berry":"命中果",
    "Custap Berry":"先制果",
    "Jaboca Berry":"嘉宝果",
    "Rowap Berry":"莲雾果",
    "Roseli Berry":"玫茄果",
    "Kee Berry":"阿开果",
    "Maranga Berry":"香波果",
    "PRZCureBerry":"解麻果（2代）",
    "Mint Berry":"薄荷果（2代）",
    "PSNCureBerry":"解毒果（2代）",
    "Burnt Berry":"烧灼果（2代）",
    "Ice Berry":"冻结果（2代）",
    "MysteryBerry":"怪异果（2代）",
    "Berry":"树果（2代）",
    "Bitter Berry":"苦味果（2代）",
    "MiracleBerry":"奇迹果（2代）",
    "Gold Berry":"黄金果（2代）",


};
var QQ=$.noConflict();
function translate(originalStr){
    console.log(originalStr);
    var tmp=originalStr.trim();
    if(translations[tmp])
        return translations[tmp];
    var regex_Ability=new RegExp(/Ability: ([A-za-z- ]+[A-za-z])/);
    
    if(originalStr.match(regex_Ability)){
        originalStr=originalStr.replace(regex_Ability,"特性: ");
        if(translations[RegExp.$1]){
            originalStr+=translations[RegExp.$1];
        }
        return originalStr;
    }
    var regex_Possible_Ability=new RegExp(/Possible abilities: ([A-za-z- ]+[A-za-z])/);
    if(originalStr.match(regex_Possible_Ability)){
        originalStr=originalStr.replace(regex_Possible_Ability,"可能的特性: ");
        if(translations[RegExp.$1]){
            originalStr+=translations[RegExp.$1];
        }
        return originalStr;
    }
    var regex_Item=new RegExp(/Item: ([(A-za-z- ]+[A-za-z)])/);
    
    if(originalStr.match(regex_Item)){
        originalStr=originalStr.replace(regex_Item,"道具: ");
        if(translations[RegExp.$1]){
            originalStr+=translations[RegExp.$1];
        }
        return originalStr;
    }
    return originalStr
    //else 
    //    return originalStr
            .replace(/lost ([0-9]+)% of its health!/,"失去了$1%的生命值!")
            //.replace(/Ability: ([A-za-z ]+)/,"特性: "+translate(RegExp.$1))
            //.replace(/Ability: \/ Item: ([A-za-z ]+)/,"特性: "++"/ 道具:"+translate("$2"))
    ;
        
}
function translateElement(element){
    var elTW = document.createTreeWalker(element, NodeFilter.SHOW_Element, null, false);
    var node=null;
    while((node=elTW.nextNode())!=null){
        if(node.nodeValue){
            //console.log(QQ(node).text());
            //QQ(node).text(transl)
            //console.log(node.nodeValue+" "+node.parentNode.getAttribute("class"));
            //console.log();
            var value=node.nodeValue;
            if(value.indexOf('•')!=-1){     //技能名在鼠标移入的状态
                value=value.replace('•',"");
                value=translate(value);
                node.nodeValue="• "+value;
            }
            else
                node.nodeValue=translate(node.nodeValue);
            //node=elTW.previousNode();
            //QQ(t).remove();
        }
    }
}
(function() {
    'use strict';
    translateElement(document.getElementById('room-'));
    QQ(document).on('DOMNodeInserted',function(e){
        translateElement(e.target);
    });
    // Your code here...
})();
